# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    assets:
        version_strategy: Packeton\Service\AssetHashVersionStrategy

    cache:
        pools:
            # pool for root/packages.json
            packages_cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: strict
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
    serializer:
        default_context:
            json_encode_options: !php/const JSON_UNESCAPED_SLASHES

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
